//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingApp2.DBA
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockOrder
    {
        public int id { get; set; }
        public string UserID { get; set; }
        public int StockID { get; set; }
        public double Value { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
